### ISSUE TITLE
Wrong number of args (2) passed to: core/identity

### ISSUE THREAD

**Issue by AdamFrey** [muhuk/ring-transit-middleware#1]
With this minimal setup on `0.1.1`

```
(ns app.server
  (:require [ring.middleware.transit :refer [wrap-transit]]))

(defn handler [req]
  {:hey "there"})

(def app
  (-> handler
      (wrap-transit)))

```

This error is being thrown: 

```
clojure.lang.ArityException: Wrong number of args (2) passed to: core/identity
    at clojure.lang.AFn.throwArity(AFn.java:429)
    at clojure.lang.AFn.invoke(AFn.java:36)
    at ring.middleware.transit$wrap_transit$fn__1644.invoke(transit.clj:204)
    at ring.middleware.cors$wrap_cors$fn__1492.invoke(cors.clj:148)
        ...
```

**Comment by muhuk** [comment]
Thanks for the report. `0.1.2` should fix this.

Ultimately it needs better tests. I will add an integration test & set up Travis to test with and without Aleph.
